import "server-only";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { FILES_DIR } from "./db";

function filePath(storedName: string) {
  // Stored names are generated by us; never let a crafted name escape FILES_DIR.
  const safe = path.basename(storedName);
  return path.join(FILES_DIR, safe);
}

export async function saveFile(bytes: Uint8Array): Promise<string> {
  const storedName = `${crypto.randomUUID()}.pdf`;
  await fs.promises.mkdir(FILES_DIR, { recursive: true });
  await fs.promises.writeFile(filePath(storedName), bytes);
  return storedName;
}

export function readFile(storedName: string): Promise<Buffer> {
  return fs.promises.readFile(filePath(storedName));
}

export function deleteStoredFile(storedName: string) {
  fs.promises.rm(filePath(storedName), { force: true }).catch(() => {});
}
